#!/usr/bin/env python3

import socket
from sys import argv
import threading

def get_addr_str(addr) -> str:
    return str(addr[0]) + ":" + str(addr[1])

def send_data(client, address):
    while True:
        inp = input(f"hostconn {get_addr_str(address)}> ")
        client.send((inp + '\n').encode())

def start():
    host = socket.gethostname()
    port = int(argv[1]) if len(argv) > 1 else 6969

    s = socket.socket()

    s.bind((host, port))
    s.listen(1)

    print(f"Server started on {host}, listening on port {port}")

    c, address = s.accept()
    print(f"Connected to: {get_addr_str(address)}")

    send_thread = threading.Thread(target=send_data(c, address))
    send_thread.start()

    while True:
        # Receive data from the client (up to 1024 bytes) and decode it
        data = c.recv(1024).decode()

        # If no data is received, break the loop
        if not data:
            break
        print(f"From {get_addr_str(address)}: {data}")
    c.close()


if __name__ == "__main__":
    try:
        start()
    except KeyboardInterrupt as e:
        print("\nClosing socket")
    except PermissionError as e:
        print("Failed to start server:", e)
